<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<section>
  <div class="new-brands">New Brands</div>
  <article>
   
  </article>
  <nav class="side-part">
   <div class="nav-first">
     <span class="first-nav">My Cart</span><br/>
     <span class="second-nav">you have no items in your shopping cart</span>
   </div>
   <div class="nav-second">
     <span class="first-nav">Compare Product</span><br/>
     <span class="second-nav">you have no items to compare</span>
   </div>
   <div class="nav-third"> 
     <span class="first-nav">Best Seller</span>
   </div>
   <div class="nav-second">
     <span class="first-nav">Popular tag</span><br/>
     <span class="second-nav">apple samsung lg dell hp ipad lcd led cam zoom</span>
   </div>
  </nav>
</section>
<div class="lower-div" link="black"> 
    <table>
      <tr>
        <td><a href="#">Browse All :</a> </td>
        <td><a href="#">New Store</a> </td>
        <td><a href="#">Featured Shoes</a></td>
        <td><a href="#">A-Z</a></td>
      </tr>
    </table>
  </div>
</body>
</html>